state-spaces/mamba

- setup.py
**Issue:** Using `pip install .` was failing with the following error:
```
Building wheels for collected packages: mamba-ssm                                                                                                                                                                                                                               
Building wheel for mamba-ssm (setup.py) ... error                                                                                                                                                                                                                             
error: subprocess-exited-with-error …
```
> Minor edit to `setup.py`

- evals/lm_harness_eval.py
The error is caused by wrong parsing type in eval that pass in a string for batch_size. Maybe this should be fixed in the dependency not here...
> Fixed my previous fix 

- mamba_ssm/ops/triton/layernorm.py
This fixes https://github.com/state-spaces/mamba/issues/44.
Please refer to the issue to get more information about the bug.
> Fix: remove is_rms_norm parameter in forward method of RMSNorm class

- mamba_ssm/ops/triton/layernorm.py
Layernorm kernel fails if your tensors are not on default cuda device.
mean and rstd were allocated on default "cuda" device.
> BUGFIX: layernorm mean, rstd

- README.md
- benchmarks/benchmark_generation_mamba_simple.py
- mamba_ssm/utils/generation.py
[min_p](https://www.reddit.com/r/LocalLLaMA/comments/17vonjo/your_settings_are_probably_hurting_your_model_why/) is a popular sampling method that has been adopted by various backends, e.g exllama, llamacpp, vllm.
> Add min_p sampling method

- mamba_ssm/models/config_mamba.py
- mamba_ssm/models/mixer_seq_simple.py
I encountered problems when trying to use a Mamba model trained with untied embed + unembed weights in this codebase because `MambaLMHeadModel.tie_weights()` is always called.
This PR adds a `tie_embeddings` field to the config which defaults to true, and only ties the input + output embeddings if the config value is true.
> Don't hardcode tied embed+unembed

- setup.py
Added support for Nvidia Jetson hardware, GPUs supported:
- [Jetson AGX Orin](https://www.nvidia.com/en-us/autonomous-machines/embedded-systems/jetson-orin/), [Jetson Orin NX](https://www.nvidia.com/en-us/autonomous-machines/embedded-systems/jetson-orin/), [Jetson Orin Nano](https://www.nvidia.com/en-us/autonomous-machines/embedded-systems/jetson-orin/) 	8.7
- [Jetson AGX Xavier](https://www.nvidia.com/en-us/autonomous-machines/embedded-systems/jetson-agx-xavier/), [Jetson Xavier NX](https://www.nvidia.com/en-us/autonomous-machines/embedded-systems/jetson-xavier-nx/) 	7.2
- [Jetson TX2](https://www.nvidia.com/en-us/autonomous-machines/embedded-systems/jetson-tx2/) 	6.2
- [Jetson Nano](https://www.nvidia.com/en-us/autonomous-machines/embedded-systems/jetson-nano/) 	5.3
reference - …
> Add support for Nvidia Jetson hw

- mamba_ssm/utils/generation.py
Hey guys, quite a while ago I made a PR for min_p sampling support in Mamba,
and it was merged. 
Unfortunately, there was a small mistake in the code, which
I've discovered only later and forgot to create a PR with the fix. Sorry about that, my bad. 
News of Mamba2 release reminded me about the issue, so here is the fix.
> Fix typo in min_p sampling

- mamba_ssm/ops/triton/selective_state_update.py
- mamba_ssm/ops/triton/softplus.py
- mamba_ssm/ops/triton/ssd_chunk_state.py
This PR made mamba's triton kernels compatible to triton version >= 3.0.0.
Specifically, tl.math.log1p() was deprecated so it's replaced by "tl.math.log(tl.math.exp(dt) + 1)".
> make selective ssm and ssd triton kernels compatible with the latest triton

- csrc/selective_scan/selective_scan_bwd_kernel.cuh
- csrc/selective_scan/selective_scan_fwd_kernel.cuh
- setup.py
This PR is a small follow-up fix to the recently merged PR [#359 ](https://github.com/state-spaces/mamba/pull/359)
We changed the way we handle conditional compilation for kernel launches. On certain AMD architectures we were getting a compile time error due to code with an unsupported warp size even though the code is not reachable at run time. We now pass a ROCM_WARP_SIZE compile flag from setup.py and do conditional compilation based on it, using preprocessing directives.
There is also a minor typo fix in the warning text.
> ROCm warp size fix [AMD official]

- csrc/selective_scan/selective_scan_bwd_kernel.cuh
- csrc/selective_scan/selective_scan_fwd_kernel.cuh
- setup.py
This PR addresses the issue https://github.com/state-spaces/mamba/issues/412
This install error is caused by a bug related to the warp size of Radeon GPUs in one of the ROCm libraries (rocprim). As a result, the warp size 32 based kernel launch fails to compile. In this fix, we use the same kernel parameters for both Instinct and Radeon GPUs. The performance hit is negligible.
The bug in rocmprim has been fixed (https://github.com/ROCm/rocPRIM/issues/542) but is not in the release yet. We can open another PR to revert the code once this rocprim fix is in the release.
> Fix for Issue #412 [AMD official]

- setup.py
Encountered an issue when building:
`packaging.version.InvalidVersion: Invalid version: '6.0.32831+'`
This error occurs in:
`rocm_version = parse(line.split()[-1].replace("-", "+"))`
The current implementation replaces "-" with "+" in version strings, that can leave a trailing "+" that violates PEP 440 standards. 
The same issue could occur here:
`return parse(torch.version.hip.split()[-1].replace("-", "+"))`
> Fix ROCm version parsing

- mamba_ssm/modules/mamba2.py
Hi @tridao and team,
I wrote a quick PoC to showcase that you can easily have integration with the 🤗 hub so that you can automatically load the various Mamba models using `from_pretrained` (and push them using `push_to_hub`), track download numbers for your models (similar to models in the Transformers library), and have nice model cards on a per-model basis. It leverages the [PyTorchModelHubMixin](https://huggingface.co/docs/huggingface_hub/package_reference/mixins#huggingface_hub.PyTorchModelHubMixin) class which allows to inherits these methods.
Yes this works for any custom PyTorch models, it's not limited to Transformers/Diffusers :)
Usage is as follows:
```python
from mamba_ssm import Mamba2
model = Mamba2(
d_model=dim, # Model dimension d_model
d_state=64,  # SSM state expansion …
```
> Add HF integration, better discoverability

- tests/ops/triton/test_selective_state_update.py
Dear author, 
We noticed that the unittest `test_selective_state_update_with_heads` was added in [some recent commit](https://github.com/state-spaces/mamba/commit/346230250920130803836b83dec895637305e466), but when we tried to run `pytest tests/`, we found an error occured:
`NameError: name 'repeat' is not defined`.
So we add the missing import part of `from einops import repeat`, and it works.
Hope it helps!
> Fix unittest for test_selective_state_update_with_heads

- README.md
- pyproject.toml
- setup.py
Now you can just pip install mamba_ssm and it will work, previously it would throw unless you had `packaging` and `torch` already installed. It would also always fail if you had build isolation on (which will be on by default in the future within `pip`).
As a side effect, now `uv` can `uv pip install mamba_ssm` properly now.
Take note that installing `causal-conv1d` via the optional extra will still fail with build isolation due to that package needing similar changes to this one.
> Make properly pip installable without needing build isolation (uv pip install now works too)

- .github/workflows/publish.yaml
Update wheels publishing now that pytorch 2.4.0 is out and it also seems to support CUDA 12.4 too
> add support for pytorch 2.4.0 with cuda 12.4

- mamba_ssm/ops/triton/ssd_combined.py
Thank you for your amazing work,
This PR fixes the issues #529 #522 #401 . The issue is in the `layer_norm_bwd` function where the `group_size` was not properly accounted for when `ngroups` is larger than one. Previously, the `group_size` defaulted to the entire SSM dimension. This should solve the exploding gradients caused by `ngroups` larger than one or than TP in case of Tensor Parallelism.
> Fix Consider group_size in layer_norm_bwd

- mamba_ssm/modules/mamba2.py
Addresses two errors when use_eff_mem_path is set to False (to avoid causal_conv1d):
1) There is a typo at line 233 - currently the class references self.dconv (which doesn't exist) instead of self.d_conv. This gives rise to an attribute missing error.
2) Assuming I've understood correctly, the original code indexes the post-conv1d tensor incorrectly. For example, if the sequence length were 20 and the post-conv1d tensor has length 23, it is indexed to the last 3 items rather than the first 20.
> Fixes typo when indexing after self.conv1d

- mamba_ssm/distributed/tensor_parallel.py
- mamba_ssm/ops/selective_scan_interface.py
- mamba_ssm/ops/triton/layer_norm.py
- mamba_ssm/ops/triton/ssd_combined.py
Hey, 
I noticed some weird comments started popping up after the torch update. Maybe we should fix that to make it perfect?
Best,
Fedor
> Fixed nasty warnings, after torch.cuda.amp went to torch.amp

- mamba_ssm/distributed/tensor_parallel.py
- mamba_ssm/ops/selective_scan_interface.py
- mamba_ssm/ops/triton/layer_norm.py
- mamba_ssm/ops/triton/ssd_combined.py
- mamba_ssm/utils/torch.py
Fixes #594
Fixes #496 
Fixes #517
#584 broke main for torch with older versions, e.g. torch==2.2.0. There have been similar attempts at #501 and #560
The main difference is to create a wrapper around the decorator that passes the new kwarg if necessary and changes the import depending on what torch version we have (based on if amp has custom_(fwd|bwd)). I moved it to the utils folder, open to change the structure.
P.S. Verified the fix with torch=2.2.0 (older version who doesn't have custom_(fwd|bwd) in amp) and torch=2.5.0 (newer version who does have custom_(fwd|bwd) in amp).
> Fix custom fwd and bwd for older PyTorch versions

- mamba_ssm/ops/triton/ssd_chunk_scan.py
Hey Tri and Albert,
Digging through the code base, I have found a bug in the backward pass for the gradient calculations in the function `_chunk_scan_bwd_ddAcs_stable_kernel`. I think this solves the issue given by #503, however, it will definitely fix incorrect gradient calculations for $\Delta A$.
Essentially, all that was going on lines [1146-1149](https://github.com/Hprairie/mamba/blob/b069d47659435f613d3820d6f5a5e188ad46a4f2/mamba_ssm/ops/triton/ssd_chunk_scan.py#L1146) if `BLOCK_SIZE_N` was greater then `BLOCK_SIZE_M` then it would update the pointer by `BLOCK_SIZE_N`. Then when we try to zero out the remainder of the sequence in lines [1152:1154](https://github.com/Hprairie/mamba/blob/b069d47659435f613d3820d6f5a5e188ad46a4f2/mamba_ssm/ops/triton/ssd_chunk_scan.py#L1152), the loop …
> Fix Incorrect Gradients and Illegal Memory Access Error in Mamba2

- README.md
Clarifying that "no build isolation" option might help with other problems, not only PyTorch versions.
> Clarifying no build isolation instructions

- mamba_ssm/ops/triton/selective_state_update.py
- tests/ops/triton/test_selective_state_update.py
See also https://github.com/Dao-AILab/causal-conv1d/pull/29
Currently, the state passed to selective_state_update must be represented a single tensor. This leads to difficulties with the management of the state for Jamba models in vLLM. This is because with continuous batching, the items in the current batch have arrived at different times, and their associated state is therefore allocated at different times and therefore likely different places.
The initial Jamba support in vLLM https://github.com/vllm-project/vllm/pull/4115 dealt with this by allocating two buffers and copied the state for the current batch into a contiguous tensor. A subsequent PR https://github.com/vllm-project/vllm/pull/6739 added some bookkeeping to remove that extra memory and to reduce overhead from copying the …
> Change interface to selective_state_update for continuous batching

- mamba_ssm/ops/selective_scan_interface.py
Hi Albert Gu and Tri Dao,
First of all, thank you for this package. We would like to upstream some changes that were needed to train the [FalconMamba-7B](https://huggingface.co/blog/falconmamba) model using the mamba kernels. 
This PR introduces a way to pass non learnable RMS norm weights in order to normalize B, C and dt states as per our training procedure. 
Another way could be to initialize `weight` in `rms_norm_forward` with `torch.ones_like`, but I'd prefer to force users to pass the non learnable parameters themselves to avoid multiple tensor initialization at each call of `mamba_inner_fn`, there might be a way to call the rms norm forward without having the need to pass RMS weights which I am not sure. 
On transformers side, we would call the interface with the following: …
> Feat: Add the support for non-learnable RMS norm for large-scale training in `mamba_inner_fn`

- pyproject.toml
- setup.py
Added triton as dependency.
Otherwise it fails on import:
```
$ python -c 'import mamba_ssm'
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/tmp/coulombc/26517/lib/python3.11/site-packages/mamba_ssm/__init__.py", line 3, in <module>
from mamba_ssm.ops.selective_scan_interface import selective_scan_fn, mamba_inner_fn
File "/tmp/coulombc/26517/lib/python3.11/site-packages/mamba_ssm/ops/selective_scan_interface.py", line 16, in <module>
from mamba_ssm.ops.triton.layer_norm import _layer_norm_fwd
File "/tmp/coulombc/26517/lib/python3.11/site-packages/mamba_ssm/ops/triton/layer_norm.py", line 16, in <module>
import triton
ModuleNotFoundError: No module named 'triton'
```
> Add triton as dependency

- mamba_ssm/ops/triton/ssd_chunk_scan.py
- mamba_ssm/ops/triton/ssd_chunk_state.py
- mamba_ssm/ops/triton/ssd_combined.py
This PR adds the following:
1. Differences of negative numbers that should be negative are clamped to zero. In most cases this clamping has no effect. In the case where numerical error leads the difference to be positive, this clamping prevents a positive number from being exponentiated leading to infinities/nans.
2. xBC is made contiguous before causal_conv1d to prevent a stride error (`RuntimeError: causal_conv1d with channel last layout requires strides (x.stride(0) and x.stride(2)) to be multiples of 8`) from being thrown when the number of heads is not a multiple of 8. With this patch, the number of heads can be any positive integer.
3. A ddt -> dt typo is fixed
> Add numerical instability patch and enable nheads to be a non multiple of 8 

- mamba_ssm/ops/triton/ssd_chunk_state.py
Re-introducing an exponential which was dropped when introducing clamping in this [PR](https://github.com/state-spaces/mamba/pull/713).
> Fix _chunk_state_bwd_db_kernel: an exp got drop during a previous PR
